<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // enrollment_kelas
        DB::table('enrollment_kelas')->insert([
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // enrollment_mahasiswa
        DB::table('enrollment_mahasiswa_kelas')->insert([
            [
                'id_mahasiswa' => 1,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 2,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 3,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 4,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 5,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 6,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 7,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 8,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 9,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 10,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 11,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 12,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 13,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 14,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 15,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 16,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 17,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 18,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 19,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 20,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 21,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 22,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 23,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);

        // mata_kuliah
        DB::table('mata_kuliah')->insert([
            [
                'kode_matkul' => '331-241-2010',
                'nama_matkul' => 'Bahasa Inggris Teknik I ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2020',
                'nama_matkul' => 'Elektronika Digital ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2030',
                'nama_matkul' => 'Kewarganegaraan ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2040',
                'nama_matkul' => 'Matematika Teknik ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2051',
                'nama_matkul' => 'Mesin Listrik DC ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2060',
                'nama_matkul' => 'Algoritma dan Pemrograman ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2071',
                'nama_matkul' => 'Praktek Dasar Instalasi Listrik ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2081',
                'nama_matkul' => 'Praktikum Listrik Dasar ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2090',
                'nama_matkul' => 'Rancangan Instalasi Listrik Lanjut ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-2100',
                'nama_matkul' => 'Rangkaian Listrik AC',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2020',
                'nama_matkul' => 'Matematika II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2030',
                'nama_matkul' => 'Rangkaian Listrik II ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2040',
                'nama_matkul' => 'Elektronika Digital II ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2050',
                'nama_matkul' => 'Elektronika Analog II ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2060',
                'nama_matkul' => 'Sensor dan Transduser ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2070',
                'nama_matkul' => 'Mesin Listrik ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2080',
                'nama_matkul' => 'Elektronika Daya ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2091',
                'nama_matkul' => 'Bengkel Elektronika II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2101',
                'nama_matkul' => 'Laboratorium Rangkaian Listrik ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2111',
                'nama_matkul' => 'Laboratorium Elektronika Digital ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2121',
                'nama_matkul' => 'Laboratorium Elektronika Analog ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-2131',
                'nama_matkul' => 'Laboratorium Pemrograman II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2010',
                'nama_matkul' => 'Bahasa Indonesia ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2020',
                'nama_matkul' => 'Bahasa Inggris Teknik I ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2030',
                'nama_matkul' => 'Elektronika Digital ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2041',
                'nama_matkul' => 'Praktikum Rancangan Listrik II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2050',
                'nama_matkul' => 'Kewarganegaraan ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2060',
                'nama_matkul' => 'Matematika Lanjut ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2070',
                'nama_matkul' => 'Mesin Listrik DC ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2080',
                'nama_matkul' => 'Praktek Dasar Instalasi Listrik ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2081',
                'nama_matkul' => 'Praktek Dasar Instalasi Listrik ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2090',
                'nama_matkul' => 'Praktikum Listrik Dasar ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-2091',
                'nama_matkul' => 'Praktikum Listrik Dasar ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2020',
                'nama_matkul' => 'Matematika Teknik II ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2030',
                'nama_matkul' => 'Elektronika Digital I ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2040',
                'nama_matkul' => 'Elektronika Analog I ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2050',
                'nama_matkul' => 'Rangkaian Listrik II ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2060',
                'nama_matkul' => 'Mesin Listrik ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2071',
                'nama_matkul' => 'Bengkel Elektronika II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2081',
                'nama_matkul' => 'Praktikum Elektronika Digital I ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2101',
                'nama_matkul' => 'Praktikum Rangkaian Listrik II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2111',
                'nama_matkul' => 'Praktikum Mesin Listrik ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2121',
                'nama_matkul' => 'Pemrograman Komputer II ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-2191',
                'nama_matkul' => 'Praktikum Elektronika Analog I ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4020',
                'nama_matkul' => 'K3LH ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4030',
                'nama_matkul' => 'Managemen Industri dan Projek ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4041',
                'nama_matkul' => 'Pemrograman Komputer',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4050',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4051',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4061',
                'nama_matkul' => 'Proteksi Sistem Tenaga ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4071',
                'nama_matkul' => 'Praktikum PLC ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4070',
                'nama_matkul' => 'Praktikum PLC ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4080',
                'nama_matkul' => 'Praktikum TTL ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4081',
                'nama_matkul' => 'Praktikum TTL ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4091',
                'nama_matkul' => 'Praktikum ELDA dan Sistem Kendali ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4090',
                'nama_matkul' => 'Praktikum ELDA dan Sistem Kendali ',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-4101',
                'nama_matkul' => 'Utilitas Industri dan Komersial',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4020',
                'nama_matkul' => 'Mikrokontroler II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4030',
                'nama_matkul' => 'Programmable Logic Controller II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4041',
                'nama_matkul' => 'Sistem Kendali Kontinu',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4050',
                'nama_matkul' => 'Kendali Berbasis Komputer I',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4060',
                'nama_matkul' => 'Instrumentasi II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4071',
                'nama_matkul' => 'Desain dan Proyek Elektronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4081',
                'nama_matkul' => 'Laboratorium Mikrokontroler II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4091',
                'nama_matkul' => 'Laboratorium PLC II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4101',
                'nama_matkul' => 'Laboratorium Sistem Kendali Kontinu',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4111',
                'nama_matkul' => 'Kendali Berbasis Komputer I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-4121',
                'nama_matkul' => 'Laboratorium Instrumentasi',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4020',
                'nama_matkul' => 'Analisis Sistem Tenaga I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4030',
                'nama_matkul' => 'Mesin Mesin Listrik Lanjut',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4040',
                'nama_matkul' => 'PLC I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4050',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4051',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4061',
                'nama_matkul' => 'Praktikum Kendali Mikro I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4070',
                'nama_matkul' => 'Praktikum Teknik Tenaga Listrik',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4071',
                'nama_matkul' => 'Praktikum Teknik Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4080',
                'nama_matkul' => 'Rancangan Projek Instalasi Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-4090',
                'nama_matkul' => 'Transmisi Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-4100',
                'nama_matkul' => 'Elektronika Daya II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4020',
                'nama_matkul' => 'Instrumentasi I',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4030',
                'nama_matkul' => 'Mekatronika',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4040',
                'nama_matkul' => 'Elektronika Daya',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4050',
                'nama_matkul' => 'Mikrokontroler II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4060',
                'nama_matkul' => 'PLC II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4070',
                'nama_matkul' => 'Sistem Kendali Analog',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4081',
                'nama_matkul' => 'Praktikum Instrumentasi I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4091',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4101',
                'nama_matkul' => 'Praktikum Elektronika Daya',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4111',
                'nama_matkul' => 'Praktikum Mikrokontroler II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4121',
                'nama_matkul' => 'Praktikum PLC II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-4131',
                'nama_matkul' => 'Praktikum Sistem Kendali Analog',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6021',
                'nama_matkul' => 'Mekatronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6031',
                'nama_matkul' => 'Pendidikan Agama',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6040',
                'nama_matkul' => 'PPKn',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6051',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6051',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6061',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6071',
                'nama_matkul' => 'Praktikum Kendali Mikro',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6080',
                'nama_matkul' => 'SCADA',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-6090',
                'nama_matkul' => 'Software Aplikasi Ketenagalistrikan ',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6020',
                'nama_matkul' => 'Bahasa Inggris III',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6030',
                'nama_matkul' => 'K3 dan Lingkungan',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6040',
                'nama_matkul' => 'Perawatan dan Perbaikan',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6050',
                'nama_matkul' => 'Kendali Berbasis Komputer II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6060',
                'nama_matkul' => 'Sistem Kendali Diskrit',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6070',
                'nama_matkul' => 'Internet of Things',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6081',
                'nama_matkul' => 'Laboratorium Perawatan dan Perbaikan',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6091',
                'nama_matkul' => 'Laboratorium Kendali Berbasis Komputer II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6101',
                'nama_matkul' => 'Laboratorium Sistem Kendali Diskrit',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-6111',
                'nama_matkul' => 'Laboratorium Internet of Things',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6020',
                'nama_matkul' => 'Mekatronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6030',
                'nama_matkul' => 'Metode Penelitian',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6040',
                'nama_matkul' => 'Operasi Sistem Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6050',
                'nama_matkul' => 'Penggunaan Komputer pada AST',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6061',
                'nama_matkul' => 'Praktek Jaringan Tegangan Menengah',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6071',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6071',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6080',
                'nama_matkul' => 'Proteksi Sistem Tenaga',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6090',
                'nama_matkul' => 'SCADA',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-6100',
                'nama_matkul' => 'Utilitas Industri dan Komersial',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6020',
                'nama_matkul' => 'Metodologi Penelitian dan Karya Ilmiah',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6030',
                'nama_matkul' => 'Sistem Terbenam',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6040',
                'nama_matkul' => 'Kendali Berbasis Komputer II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6050',
                'nama_matkul' => 'Internet of Things (IoT)',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6060',
                'nama_matkul' => 'Robotika II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6070',
                'nama_matkul' => 'Kendali Cerdas',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6081',
                'nama_matkul' => 'Praktikum Perawatan dan Perbaikan',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6091',
                'nama_matkul' => 'Praktikum Sistem Terbenam',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6101',
                'nama_matkul' => 'Praktikum Kendali Berbasis Komputer II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6111',
                'nama_matkul' => 'Praktikum Internet of Things (IoT)',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6121',
                'nama_matkul' => 'Praktikum Robotika II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-6131',
                'nama_matkul' => 'Praktikum Kendali Cerdas',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8020',
                'nama_matkul' => 'K3LH',
                'sks' => 2,
                'jam' => 4,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8030',
                'nama_matkul' => 'Kualitas Daya Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8040',
                'nama_matkul' => 'Optimasi Sistem Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8051',
                'nama_matkul' => 'Praktikum ELDA dan Sistem Kendali',
                'sks' => 2,
                'jam' => 8,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8061',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 8,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-8071',
                'nama_matkul' => 'Praktikum Sistem Proteksi dan Rele',
                'sks' => 2,
                'jam' => 4,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
