<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // enrollment_kelas
        DB::table('enrollment_kelas')->insert([
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // enrollment_mahasiswa
        DB::table('enrollment_mahasiswa_kelas')->insert([
            [
                'id_mahasiswa' => 1,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 2,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 3,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 4,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 5,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 6,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 7,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 8,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 9,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 10,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 11,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 12,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 13,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 14,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 15,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 16,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 17,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 18,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 19,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 20,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 21,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 22,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 23,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);

        // mata_kuliah
        DB::table('mata_kuliah')->insert([
            [
                'kode_matkul' => 'MTKL1',
                'nama_matkul' => 'Teknik Digital dan Sistem Tertanam',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL2',
                'nama_matkul' => 'Teknik Digital dan Sistem Tertanam',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL3',
                'nama_matkul' => 'Bahasa Inggris 1',
                'sks' => 2,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL4',
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => 2,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL5',
                'nama_matkul' => 'Sistem Basis Data II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL6',
                'nama_matkul' => 'Sistem Basis Data II',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL7',
                'nama_matkul' => 'Kecerdasan Buatan',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL8',
                'nama_matkul' => 'Kecerdasan Buatan',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL9',
                'nama_matkul' => 'Pemrograman Berorientasi Objek',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL10',
                'nama_matkul' => 'Pemrograman Berorientasi Objek',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL11',
                'nama_matkul' => 'Jaringan Komputer I',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL12',
                'nama_matkul' => 'Jaringan Komputer I',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL13',
                'nama_matkul' => 'Statistika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL14',
                'nama_matkul' => 'Pancasila',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL15',
                'nama_matkul' => 'Pembelajaran Mesin',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL16',
                'nama_matkul' => 'Pembelajaran Mesin',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL17',
                'nama_matkul' => 'Keamanan Jaringan',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL18',
                'nama_matkul' => 'Interoperabilitas',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL19',
                'nama_matkul' => 'Interoperabilitas',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL20',
                'nama_matkul' => 'Pemrograman Game',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL21',
                'nama_matkul' => 'Pemrograman Game',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL22',
                'nama_matkul' => 'Pemrograman Web Framework',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL23',
                'nama_matkul' => 'Pemrograman Web Framework',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL24',
                'nama_matkul' => 'Pengolahan Citra',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL25',
                'nama_matkul' => 'Pengolahan Citra',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL26',
                'nama_matkul' => 'Keamanan Jaringan',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL27',
                'nama_matkul' => 'Sistem Informasi Enterprise',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL28',
                'nama_matkul' => 'Sistem Informasi Enterprise',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL29',
                'nama_matkul' => 'Pengembangan Game',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL30',
                'nama_matkul' => 'Pengembangan Game',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL31',
                'nama_matkul' => 'Real Time Sistem',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL32',
                'nama_matkul' => 'Real Time Sistem',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL33',
                'nama_matkul' => 'Simulasi dan Pemrograman Robot',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL34',
                'nama_matkul' => 'Simulasi dan Pemrograman Robot',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL35',
                'nama_matkul' => 'Big Data',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL36',
                'nama_matkul' => 'Big Data',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL37',
                'nama_matkul' => 'Manajemen Proyek',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL38',
                'nama_matkul' => 'Technopreneurship',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL39',
                'nama_matkul' => 'Bahasa Indonesia',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL40',
                'nama_matkul' => 'Skripsi 1',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL41',
                'nama_matkul' => 'Skripsi 1',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL42',
                'nama_matkul' => 'Skripsi 2',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL43',
                'nama_matkul' => 'Skripsi 2',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL44',
                'nama_matkul' => 'Etika Profesi',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL45',
                'nama_matkul' => 'Integerative Programming',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL46',
                'nama_matkul' => 'Automatisasi Industri',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL47',
                'nama_matkul' => 'Special Topic in Industrial Informatic',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL48',
                'nama_matkul' => 'Metodologi Penelitian',
                'sks' => 1,
                'jam' => 2,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => 'MTKL49',
                'nama_matkul' => 'Virtual System & Services',
                'sks' => 2,
                'jam' => 4,
                'semester' => '3',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
