<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // enrollment_kelas
        DB::table('enrollment_kelas')->insert([
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 1,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 2,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_tahun_akademik' => 1,
                'id_program_studi' => 1,
                'id_kelas' => 3,
                'id_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // enrollment_mahasiswa_kelas
        DB::table('enrollment_mahasiswa_kelas')->insert([
            [
                'id_mahasiswa' => 1,
                'id_enrollment_kelas' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 2,
                'id_enrollment_kelas' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 3,
                'id_enrollment_kelas' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 4,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 5,
                'id_enrollment_kelas' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 6,
                'id_enrollment_kelas' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 7,
                'id_enrollment_kelas' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 8,
                'id_enrollment_kelas' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 9,
                'id_enrollment_kelas' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 10,
                'id_enrollment_kelas' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 11,
                'id_enrollment_kelas' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 12,
                'id_enrollment_kelas' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 13,
                'id_enrollment_kelas' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 14,
                'id_enrollment_kelas' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 15,
                'id_enrollment_kelas' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 16,
                'id_enrollment_kelas' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 17,
                'id_enrollment_kelas' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 18,
                'id_enrollment_kelas' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 19,
                'id_enrollment_kelas' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 20,
                'id_enrollment_kelas' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 21,
                'id_enrollment_kelas' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 22,
                'id_enrollment_kelas' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mahasiswa' => 23,
                'id_enrollment_kelas' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // mata_kuliah
        DB::table('mata_kuliah')->insert([
            [
                'kode_matkul' => '331-241-201',
                'nama_matkul' => 'Bahasa Inggris Teknik I',
                'sks' => 2,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-202',
                'nama_matkul' => 'Elektronika Digital',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-203',
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => 2,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-204',
                'nama_matkul' => 'Matematika Teknik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-205',
                'nama_matkul' => 'Mesin Listrik DC',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-206',
                'nama_matkul' => 'Algoritma dan Pemrograman',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-207',
                'nama_matkul' => 'Praktek Dasar Instalasi Listrik',
                'sks' => 2,
                'jam' => 6,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-208',
                'nama_matkul' => 'Praktikum Listrik Dasar',
                'sks' => 2,
                'jam' => 6,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-209',
                'nama_matkul' => 'Rancangan Instalasi Listrik Lanjut',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-241-210',
                'nama_matkul' => 'Rangkaian Listrik AC',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-201',
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-202',
                'nama_matkul' => 'Matematika II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-203',
                'nama_matkul' => 'Rangkaian Listrik II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-204',
                'nama_matkul' => 'Elektronika Digital II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-205',
                'nama_matkul' => 'Elektronika Analog II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-206',
                'nama_matkul' => 'Sensor dan Transduser',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-207',
                'nama_matkul' => 'Mesin Listrik',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-208',
                'nama_matkul' => 'Elektronika Daya',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-209',
                'nama_matkul' => 'Bengkel Elektronika II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-210',
                'nama_matkul' => 'Laboratorium Rangkaian Listrik',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-211',
                'nama_matkul' => 'Laboratorium Elektronika Digital',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-212',
                'nama_matkul' => 'Laboratorium Elektronika Analog',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-241-213',
                'nama_matkul' => 'Laboratorium Pemrograman II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-231-210',
                'nama_matkul' => 'Rangkaian Listrik II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-201',
                'nama_matkul' => 'Bahasa Indonesia',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-202',
                'nama_matkul' => 'Bahasa Inggris Teknik I',
                'sks' => 1,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-203',
                'nama_matkul' => 'Elektronika Digital',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-204',
                'nama_matkul' => 'Praktikum Rancangan Listrik II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-205',
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => 2,
                'jam' => 2,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-206',
                'nama_matkul' => 'Matematika Lanjut',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-207',
                'nama_matkul' => 'Mesin Listrik DC',
                'sks' => 2,
                'jam' => 4,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-208',
                'nama_matkul' => 'Praktek Dasar Instalasi Listrik',
                'sks' => 3,
                'jam' => 6,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-241-209',
                'nama_matkul' => 'Praktikum Listrik Dasar',
                'sks' => 2,
                'jam' => 6,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-201',
                'nama_matkul' => 'Pendidikan Kewarganegaraan',
                'sks' => 2,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-202',
                'nama_matkul' => 'Matematika Teknik II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-203',
                'nama_matkul' => 'Elektronika Digital I',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-204',
                'nama_matkul' => 'Elektronika Analog I',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-205',
                'nama_matkul' => 'Rangkaian Listrik II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-206',
                'nama_matkul' => 'Mesin Listrik',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-207',
                'nama_matkul' => 'Bengkel Elektronika II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-208',
                'nama_matkul' => 'Praktikum Elektronika Digital I',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-210',
                'nama_matkul' => 'Praktikum Rangkaian Listrik II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-211',
                'nama_matkul' => 'Praktikum Mesin Listrik',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-212',
                'nama_matkul' => 'Pemrograman Komputer II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-241-219',
                'nama_matkul' => 'Praktikum Elektronika Analog I',
                'sks' => 2,
                'jam' => 3,
                'semester' => '2',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-401',
                'nama_matkul' => 'Instalasi Tegangan Menengah',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-402',
                'nama_matkul' => 'K3LH',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-403',
                'nama_matkul' => 'Managemen Industri dan Projek',
                'sks' => 1,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-404',
                'nama_matkul' => 'Pemrograman Komputer',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-405',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri',
                'sks' => 2,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-406',
                'nama_matkul' => 'Proteksi Sistem Tenaga',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-407',
                'nama_matkul' => 'Praktikum PLC',
                'sks' => 2,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-408',
                'nama_matkul' => 'Praktikum TTL',
                'sks' => 3,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-409',
                'nama_matkul' => 'Praktikum ELDA dan Sistem Kendali',
                'sks' => 2,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-410',
                'nama_matkul' => 'Utilitas Industri dan Komersial',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-401',
                'nama_matkul' => 'Bahasa Inggris II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-402',
                'nama_matkul' => 'Mikrokontroler II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-403',
                'nama_matkul' => 'Programmable Logic Controller II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-404',
                'nama_matkul' => 'Sistem Kendali Kontinu',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-405',
                'nama_matkul' => 'Kendali Berbasis Komputer I',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-406',
                'nama_matkul' => 'Instrumentasi II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-407',
                'nama_matkul' => 'Desain dan Proyek Elektronika',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-408',
                'nama_matkul' => 'Laboratorium Mikrokontroler II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-409',
                'nama_matkul' => 'Laboratorium PLC II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-410',
                'nama_matkul' => 'Laboratorium Sistem Kendali Kontinu',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-411',
                'nama_matkul' => 'Laboratorium Kendali Berbasis Komputer I',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-412',
                'nama_matkul' => 'Laboratorium Instrumentasi',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-401',
                'nama_matkul' => 'Bahasa Inggris Teknik III',
                'sks' => 2,
                'jam' => 2,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-402',
                'nama_matkul' => 'Analisis Sistem Tenaga I',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-403',
                'nama_matkul' => 'Mesin Mesin Listrik Lanjut',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-404',
                'nama_matkul' => 'PLC I',
                'sks' => 2,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-405',
                'nama_matkul' => 'Praktek Instalasi Listrik Industri',
                'sks' => 3,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-406',
                'nama_matkul' => 'Praktikum Kendali Mikro I',
                'sks' => 2,
                'jam' => 5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-407',
                'nama_matkul' => 'Praktikum Teknik Tenaga Listrik',
                'sks' => 3,
                'jam' => 6,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-408',
                'nama_matkul' => 'Rancangan Projek Instalasi Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-191-409',
                'nama_matkul' => 'Transmisi Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-410',
                'nama_matkul' => 'Elektronika Daya II',
                'sks' => 2,
                'jam' => 4,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-401',
                'nama_matkul' => 'Bahasa Inggris Teknik I',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-402',
                'nama_matkul' => 'Instrumentasi I',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-403',
                'nama_matkul' => 'Mekatronika',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-404',
                'nama_matkul' => 'Elektronika Daya',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-405',
                'nama_matkul' => 'Mikrokontroler II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-406',
                'nama_matkul' => 'PLC II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-407',
                'nama_matkul' => 'Sistem Kendali Analog',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-408',
                'nama_matkul' => 'Praktikum Instrumentasi I',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-409',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-410',
                'nama_matkul' => 'Praktikum Elektronika Daya',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-411',
                'nama_matkul' => 'Praktikum Mikrokontroler II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-412',
                'nama_matkul' => 'Praktikum PLC II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-413',
                'nama_matkul' => 'Praktikum Sistem Kendali Analog',
                'sks' => 2,
                'jam' => 3,
                'semester' => '4',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-601',
                'nama_matkul' => 'Kewirausahaan',
                'sks' => 1,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-602',
                'nama_matkul' => 'Mekatronika',
                'sks' => 2,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-603',
                'nama_matkul' => 'Pendidikan Agama',
                'sks' => 2,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-604',
                'nama_matkul' => 'PPKn',
                'sks' => 3,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-605',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 3,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-606',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-607',
                'nama_matkul' => 'Praktikum Kendali Mikro',
                'sks' => 2,
                'jam' => 5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '331-211-608',
                'nama_matkul' => 'SCADA',
                'sks' => 2,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-601',
                'nama_matkul' => 'Kewarganegaraan',
                'sks' => 2,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-602',
                'nama_matkul' => 'Bahasa Inggris III',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-603',
                'nama_matkul' => 'K3 dan Lingkungan',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-604',
                'nama_matkul' => 'Perawatan dan Perbaikan',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-605',
                'nama_matkul' => 'Kendali Berbasis Komputer II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-606',
                'nama_matkul' => 'Sistem Kendali Diskrit',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-607',
                'nama_matkul' => 'Internet of Things',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-608',
                'nama_matkul' => 'Laboratorium Perawatan dan Perbaikan',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-609',
                'nama_matkul' => 'Laboratorium Kendali Berbasis Komputer II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-610',
                'nama_matkul' => 'Laboratorium Sistem Kendali Diskrit',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '332-201-611',
                'nama_matkul' => 'Laboratorium Internet of Things',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-601',
                'nama_matkul' => 'Instalasi Tegangan Menengah',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-602',
                'nama_matkul' => 'Mekatronika',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-603',
                'nama_matkul' => 'Metode Penelitian',
                'sks' => 2,
                'jam' => 2,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-604',
                'nama_matkul' => 'Operasi Sistem Tenaga Listrik',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-605',
                'nama_matkul' => 'Penggunaan Komputer pada Teknologi',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-606',
                'nama_matkul' => 'Praktek Jaringan Tegangan Menengah',
                'sks' => 2,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-607',
                'nama_matkul' => 'Praktek Otomasi Industri',
                'sks' => 3,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-608',
                'nama_matkul' => 'Proteksi Sistem Tenaga',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-609',
                'nama_matkul' => 'SCADA',
                'sks' => 2,
                'jam' => 6,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-610',
                'nama_matkul' => 'Utilitas Industri dan Komersial',
                'sks' => 2,
                'jam' => 4,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-601',
                'nama_matkul' => 'Bahasa Inggris Teknik III',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-602',
                'nama_matkul' => 'Metodologi Penelitian dan Karya Ilmiah',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-603',
                'nama_matkul' => 'Sistem Terbenam',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-604',
                'nama_matkul' => 'Kendali Berbasis Komputer II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-605',
                'nama_matkul' => 'Internet of Things (IoT)',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-606',
                'nama_matkul' => 'Robotika II',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-607',
                'nama_matkul' => 'Kendali Cerdas',
                'sks' => 1,
                'jam' => 1.5,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-608',
                'nama_matkul' => 'Praktikum Perawatan dan Perbaikan',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-609',
                'nama_matkul' => 'Praktikum Sistem Terbenam',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-610',
                'nama_matkul' => 'Praktikum Kendali Berbasis Komputer II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-611',
                'nama_matkul' => 'Praktikum Internet of Things (IoT)',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-612',
                'nama_matkul' => 'Praktikum Robotika II',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '434-211-613',
                'nama_matkul' => 'Praktikum Kendali Cerdas',
                'sks' => 2,
                'jam' => 3,
                'semester' => '6',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-801',
                'nama_matkul' => 'Etika Profesi',
                'sks' => 2,
                'jam' => 2,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-802',
                'nama_matkul' => 'K3LH',
                'sks' => 2,
                'jam' => 2,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-803',
                'nama_matkul' => 'Kualitas Daya Listrik',
                'sks' => 2,
                'jam' => 2,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-804',
                'nama_matkul' => 'Optimasi Sistem Tenaga Listrik',
                'sks' => 2,
                'jam' => 2,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'T',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-805',
                'nama_matkul' => 'Praktikum ELDA dan Sistem Kendali',
                'sks' => 2,
                'jam' => 8,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-806',
                'nama_matkul' => 'Praktikum Mekatronika',
                'sks' => 2,
                'jam' => 8,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_matkul' => '433-201-807',
                'nama_matkul' => 'Praktikum Sistem Proteksi dan Rele',
                'sks' => 2,
                'jam' => 6,
                'semester' => '8',
                'id_ruang' => null,
                'jenis' => 'P',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}