<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        // Dosen
        DB::table('dosen')->insert([
            //DOSEN INFORMATIKA
            [
                'nip' => '1234567801',
                'nama_dosen' => 'Sugeng Iriyanto',
                'email' => 'sugeng.iriyanto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567001',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567802',
                'nama_dosen' => 'Nur Hidayati',
                'email' => 'nur.hidayati@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567002',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567803',
                'nama_dosen' => 'Wiktasari',
                'email' => 'wiktasari@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567003',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567804',
                'nama_dosen' => 'Sirli Fahriah',
                'email' => 'sirli.fahriah@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567004',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567805',
                'nama_dosen' => 'Prayitno',
                'email' => 'prayitno@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567005',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567806',
                'nama_dosen' => 'Parsumo Rahardjo',
                'email' => 'parsumo.rahardjo@example.com',
                'password' => Hash::make('doesn2023'),
                'no_hp' => '081234567006',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567807',
                'nama_dosen' => 'Iswanti',
                'email' => 'iswanti@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567007',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567808',
                'nama_dosen' => 'DR. IR. Kurnianingsih',
                'email' => 'dr.ir.kurnianingsih@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567008',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567809',
                'nama_dosen' => 'Kuwat Santoso',
                'email' => 'kuwat.santoso@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567009',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567810',
                'nama_dosen' => 'Muttabik Fathul Lathief',
                'email' => 'muttabik.fathul.lathief@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567010',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567811',
                'nama_dosen' => 'Nurseno Bayu Aji',
                'email' => 'nurseno.bayu.aji@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567011',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567812',
                'nama_dosen' => 'Suko Tyas Pernanda',
                'email' => 'suko.tyas.pernanda@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567012',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567813',
                'nama_dosen' => 'Sapto Budi Priyatno',
                'email' => 'sapto.budi.priyatno@example.com',
                'password' => Hash::make('dosen20023'),
                'no_hp' => '081234567013',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567814',
                'nama_dosen' => 'Ir. Beno Kunto P',
                'email' => 'ir.beno.kunto.p@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567014',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567815',
                'nama_dosen' => 'Tri Raharjo Yudantoro',
                'email' => 'tri.raharjo.yudantoro@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567015',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567816',
                'nama_dosen' => 'Rio Devilito',
                'email' => 'rio.devilito@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567016',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567817',
                'nama_dosen' => 'Dosen Pembimbing',
                'email' => 'dosen.pembimbing@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567017',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567818',
                'nama_dosen' => 'Liliek Triyono',
                'email' => 'liliek.triyono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567018',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567819',
                'nama_dosen' => 'Ir. Hatmoko Tri Arianto',
                'email' => 'ir.hatmoko.tri.arianto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567019',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567820',
                'nama_dosen' => 'Dr. I Ketut Agung Enriko',
                'email' => 'dr.i.ketut.agung.enriko@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567020',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567821',
                'nama_dosen' => 'Afandi Nur Aziz Tohari',
                'email' => 'afandi.nur.aziz.thohari@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567021',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567822',
                'nama_dosen' => 'Sendayu',
                'email' => 'sendayu@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567022',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567823',
                'nama_dosen' => 'Tri Febrianto',
                'email' => 'tri.febrianto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567023',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567824',
                'nama_dosen' => 'Ditya Anggar Kusuma',
                'email' => 'ditya.anggar.kusuma@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567024',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567825',
                'nama_dosen' => 'Sukamto',
                'email' => 'sukamto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567025',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567826',
                'nama_dosen' => 'Ambyar Setiawan',
                'email' => 'ambyar.setiawan@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567026',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567827',
                'nama_dosen' => 'Amran Yobioktabera',
                'email' => 'amran.yobioktabera@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567027',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567828',
                'nama_dosen' => 'Rofiq Fauzi',
                'email' => 'rofiq.fauzi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567028',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567829',
                'nama_dosen' => 'Idhawati',
                'email' => 'idhawati@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567029',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567830',
                'nama_dosen' => 'Suwinardi',
                'email' => 'suwinardi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567030',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //DOSEN ELEKTRONIKA
            [
                'nip' => '1234567832',
                'nama_dosen' => 'Ilham Sayekti., S.T., M.KOM.',
                'email' => 'ilham.sayekti@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567032',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567833',
                'nama_dosen' => 'Devi Y., SST., MT',
                'email' => 'devi.y@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567033',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567834',
                'nama_dosen' => 'DRS., Sulistyo Wardoyo, M.ENG',
                'email' => 'sulistiyo.wardoyo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567034',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567835',
                'nama_dosen' => 'Taufiq Yulianto, S.H.,M.H.',
                'email' => 'taufiq.yulianto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567035',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567836',
                'nama_dosen' => 'Supriyati, S.T., M.KOM.',
                'email' => 'supriyati@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567036',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567837',
                'nama_dosen' => 'Tulus Pramuji, B.ENG., M.T.',
                'email' => 'tulus.pramuji@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567037',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567838',
                'nama_dosen' => 'Sri Astuti, DRA., MM.',
                'email' => 'sri.astuti@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567038',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567839',
                'nama_dosen' => 'Suryono, ST., M.ENG.',
                'email' => 'suryono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567039',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567840',
                'nama_dosen' => 'Yoso, ST., M.T.',
                'email' => 'yoso@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567040',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567841',
                'nama_dosen' => 'Dadi, ST., M.ENG.',
                'email' => 'dadi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567041',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567842',
                'nama_dosen' => 'Septiantar TN., ST., M.Tr. T.',
                'email' => 'septiantartn@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567042',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567843',
                'nama_dosen' => 'Vinda Setya Kartika, ST., MT.',
                'email' => 'vinda.setya.kartika@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567043',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567844',
                'nama_dosen' => 'Dedy Chasan Aflah M., S.T., M.T',
                'email' => 'dedy.chasan.alfiah@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567044',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567845',
                'nama_dosen' => 'Sihono, ST., M.ENG',
                'email' => 'sihono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567045',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567846',
                'nama_dosen' => 'Ronggo Widiharto',
                'email' => 'ronggo.wihono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567046',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567847',
                'nama_dosen' => 'Wahyu Sulistyo , S.T., M. Kom.',
                'email' => 'wahyu.sulistyo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567047',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567848',
                'nama_dosen' => 'M. Cahyo Ardi Prabowo, ST., M.Tr.T',
                'email' => 'cahyo.ardi.prabowo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567048',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567849',
                'nama_dosen' => 'Sri Kusumastuti., ST., M.ENG',
                'email' => 'sri.kusumastuti@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567049',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567850',
                'nama_dosen' => 'Sasongko, DRS., M.HUM',
                'email' => 'sasongko@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567050',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567852',
                'nama_dosen' => 'Radhitya Artha R., ST., MT.',
                'email' => 'radhitya.artha@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567052',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567853',
                'nama_dosen' => 'Aminuddin Rizal, ST., M.Sc.',
                'email' => 'aminuddin.rizal@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567053',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567854',
                'nama_dosen' => 'Saptaji Handayaani W., ST., M.T.Tr.',
                'email' => 'saptaji.handayani@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567054',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567855',
                'nama_dosen' => 'B. Supriyo, BSEE. M.ENG.Sc., Ph.D.',
                'email' => 'supriyo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567055',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567856',
                'nama_dosen' => 'DR. Netty Nurdiyani, DRA., M.HUM.',
                'email' => 'netty.nurdiyani@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567056',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567857',
                'nama_dosen' => 'DR. Samuel Beta K.,ING.TECH,  M.T.',
                'email' => 'samuel.beta@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567057',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567858',
                'nama_dosen' => 'Seno Aprilianto, S.T.',
                'email' => 'seno.aprilianto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567058',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567859',
                'nama_dosen' => 'Nicolas Lodawi Ouwpoly, M.Pd.',
                'email' => 'nicolas.lodawi.ouwpoly@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567059',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //DOSEN LISTRIK
            [
                'nip' => '1234567860',
                'nama_dosen' => 'Achmad Hardito,B.Tech , M.Kom',
                'email' => 'achmad.hardito@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567060',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567861',
                'nama_dosen' => 'Danu Angga Vebriyanto, M.Pd',
                'email' => 'danu.angga.vebriyanto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567061',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567862',
                'nama_dosen' => 'Dr. Mohammad Khambali, B.Eng., M.Kom.',
                'email' => 'mohammad.khambali@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567062',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567863',
                'nama_dosen' => 'Dra. Endang Triyani, M.Pd.',
                'email' => 'endang.triyani@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567063',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567864',
                'nama_dosen' => 'Drs. Amir Subagyo, M.M.',
                'email' => 'amir.subagyo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567064',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567865',
                'nama_dosen' => ' Drs. Juwarta, M.M.',
                'email' => 'juwarta@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567065',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567866',
                'nama_dosen' => 'Haris Santosa, S.T., M. Kom.',
                'email' => 'haris.santoso@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567066',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567867',
                'nama_dosen' => 'Lilik Eko Nuryanto, B.Eng., M.Kom.',
                'email' => 'lilik.eko.nuryanto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567067',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567868',
                'nama_dosen' => 'Nining Susanti,M.I.Kom',
                'email' => 'nining.susanti@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567068',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567869',
                'nama_dosen' => 'M. Bhayu bramantyo MTE',
                'email' => 'bhayu.bramantyo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567069',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567870',
                'nama_dosen' => 'Adeguna Ridlo Pramurti, S.Pd., M.Eng.',
                'email' => 'adeguna.ridlo@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567070',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567871',
                'nama_dosen' => 'Adi Wasono, B.Eng., M.Eng.',
                'email' => 'adi.wasono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567071',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567872',
                'nama_dosen' => 'Aji Hari Riyadi, S.T., M.T.',
                'email' => 'aji.hariyadi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567072',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567873',
                'nama_dosen' => 'Akhmad Jamaah, S.T., M.Eng.',
                'email' => 'akhmad.jamaah@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567073',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567874',
                'nama_dosen' => 'Dr. Priyo Adi Sesotyo, S.T., M.En.',
                'email' => 'priyo.adi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567074',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567875',
                'nama_dosen' => 'Drs. Agus Adiwismono, M.Eng.',
                'email' => 'agus.adwismono@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567075',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567877',
                'nama_dosen' => 'Ir. Mochammad Muqorrobin, M.Eng',
                'email' => 'mochammad.muqorrobin@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567077',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567878',
                'nama_dosen' => 'Setyoko, Ir.MM.',
                'email' => 'setyoko@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567078',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567879',
                'nama_dosen' => 'Pangestuningtyas Diah Larasati, S.T., M.T.',
                'email' => 'pangestuningtyas.diah@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567079',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567880',
                'nama_dosen' => ' Yusnan Badruzzaman, S.T., M.Eng.',
                'email' => 'yusnan.badruzzaman@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567080',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567881',
                'nama_dosen' => 'Dewi Anggraeni, S.Pd., M.Pd.',
                'email' => 'dewi.anggreini@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567081',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567882',
                'nama_dosen' => 'Drs. Daeng Supriyadi Pasisarha, S.T., M.Eng',
                'email' => 'daeng.supriyadi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567082',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567883',
                'nama_dosen' => 'Eko Widiarto,ST., M.Eng',
                'email' => 'eko.widiarto@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567083',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567884',
                'nama_dosen' => 'Febrina Indrasari, S.H.,M.H.',
                'email' => 'febrina.indrasari@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567084',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567885',
                'nama_dosen' => 'Shidiq Budi Perkasa, ST.MT',
                'email' => 'shidiq.budi@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567085',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567886',
                'nama_dosen' => 'Byan Bagas Pradana S.T., M.T.',
                'email' => 'byan.bagas@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567086',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567887',
                'nama_dosen' => 'Haedar Ali Fathin Naufal,ST.MT',
                'email' => 'haedar.ali@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567087',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567889',
                'nama_dosen' => 'Eriko Arvin Karuniawan S.ST., M.Eng.',
                'email' => 'eriko.arvin@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567089',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567890',
                'nama_dosen' => 'Syahid, S.T., M.Eng',
                'email' => 'syahid@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567890',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nip' => '1234567891',
                'nama_dosen' => ' Aggie Brenda Vernandes,ST.,MT',
                'email' => 'anggie.brenda@example.com',
                'password' => Hash::make('dosen2023'),
                'no_hp' => '081234567891',
                'foto_profil' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            //DOSEN TELEKOMUNIKASI
        ]);

        // Mahasiswa
        DB::table('mahasiswa')->insert([
            [
                'nim' => '4.33.23.0.01',
                'nama_mahasiswa' => 'ADRIANSYAH ALFARISYI',
                'email' => 'adriansyah.alfarisyi@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567801',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.02',
                'nama_mahasiswa' => 'AGUNG HADI ASTANTO',
                'email' => 'agung.hadi.astanto@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567802',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.03',
                'nama_mahasiswa' => 'AHMAD FARKHANI',
                'email' => 'ahmad.farkhani@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567803',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.04',
                'nama_mahasiswa' => 'ANINDHA CAHYA MULIA SALIM',
                'email' => 'anindha.cahya.mulia.salim@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567804',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.05',
                'nama_mahasiswa' => 'ARIF KURNIA RAHMAN',
                'email' => 'arif.kurnia.rahman@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567805',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.06',
                'nama_mahasiswa' => 'ATHAYA PANDU MARENO',
                'email' => 'athaya.pandu.mareno@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567806',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.07',
                'nama_mahasiswa' => 'DANIEL ADI PRATAMA',
                'email' => 'daniel.adi.pratama@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567807',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.08',
                'nama_mahasiswa' => 'DAVIN ALIFIANDA ADYTIA',
                'email' => 'davin.alifianda.adytia@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567808',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.09',
                'nama_mahasiswa' => 'FAJAR DWI FIRMANSYAH',
                'email' => 'fajar.dwi.firmansyah@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '08234567809',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.10',
                'nama_mahasiswa' => 'FITRIANA NAYLA NOVIANTI',
                'email' => 'fitriana.nayla.novianti@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678010',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.11',
                'nama_mahasiswa' => 'GILANG MAULANATA PRAMUDYA',
                'email' => 'gilang.maulanata.pramudya@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678011',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.13',
                'nama_mahasiswa' => 'ILHAM TARUPRASETYO',
                'email' => 'ilham.taruprasetyo@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678012',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.14',
                'nama_mahasiswa' => 'IRMA INNAYAH',
                'email' => 'irma.innayah@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678013',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.15',
                'nama_mahasiswa' => 'KHILDA SALSABILA AZKA',
                'email' => 'khilda.salsabila.azka@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678014',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.16',
                'nama_mahasiswa' => 'MARVELLINA DEVI WURDHANING',
                'email' => 'marvellina.devi.wurdhaning@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678015',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.17',
                'nama_mahasiswa' => 'MAULANA FAJAR ROHMANI',
                'email' => 'maulana.fajar.rohmani@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678016',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.18',
                'nama_mahasiswa' => 'MILA ROSITA DEWI',
                'email' => 'mila.rosita.dewi@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678017',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.19',
                'nama_mahasiswa' => 'MUHAMAD HAYDAR AYDIN ALHAMDANI',
                'email' => 'muhamad.haydar.aydin.alhamdani@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678018',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.20',
                'nama_mahasiswa' => 'MUHAMMAD SYAUQI MAULANA ANANSYAH',
                'email' => 'muhammad.syauqi.maulana.anansyah@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678019',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.21',
                'nama_mahasiswa' => 'MUHAMMAD ZAKIY FADHLULLAH AZHAR',
                'email' => 'muhammad.zakiy.fadhlullah.azhar@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678020',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.22',
                'nama_mahasiswa' => 'RACHMAD YOGO DWIYANTO',
                'email' => 'rachmad.yogo.dwiyanto@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678021',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.23',
                'nama_mahasiswa' => 'RAFI ARTHAYANA PUTRA DERIZMA',
                'email' => 'rafi.arthayana.putra.derizma@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678022',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nim' => '4.33.23.0.26',
                'nama_mahasiswa' => 'TUBAGUS PRATAMA JULIANTO',
                'email' => 'tubagus.pratama.julianto@student.example.com',
                'password' => Hash::make('mhs23'),
                'no_hp' => '082345678023',
                'foto_profil' => null, 
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Admin
        DB::table('admin')->insert([
            'nip' => '9876543210',
            'nama_admin' => 'Admin System',
            'email' => 'system@example.com',
            'password' => Hash::make('admin1'),
            'no_hp' => '0812345555',
            'foto_profil' => null,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        // Ruang
        DB::table('ruang')->insert([
            //RUANG INFORMATIKA
            [
                'nama_ruang' => 'GKT 801',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 802',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 803',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 804',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 805',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 806',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 807',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 810',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 201A',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 201B',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 201C',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 303',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 304',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 305',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'MST 306',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Multimedia',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Pemrograman',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Jaringan Komputer',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //Ruang Elektronika
            [
                'nama_ruang' => 'Lab Analog',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SA 203',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab EK Digital',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Ruang Gambar SB2',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Bengkel ME/EK',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Instrumen',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Labkom EK',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SA 209',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SA 208',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Mikro',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Kendali',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SA 207',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 308',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 809',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //Ruang Elektronika
            [
                'nama_ruang' => 'GKT 710',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'GKT 711',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab LT Barat',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Komputer',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Mekatronika',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Kendali Mikro',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab PLC',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab LT Timur',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Ruang Multimedia',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SB1 06',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SB1 08',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SB1 09',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'SB2 01',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'UPA Bahasa',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Workshop Timur',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Workshop Barat',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Lab Gambar',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'Ruang Maintenance-Repair',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_ruang' => 'RPL Bengkel Maintenance',
                'keterangan' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
        

        // Kelas
        DB::table('kelas')->insert([
            [
                'nama_kelas' => 'A',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kelas' => 'B',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kelas' => 'C',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kelas' => 'D',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kelas' => 'E',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Angkatan
        DB::table('angkatan')->insert([
            [
                'tahun_angkatan' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tahun_angkatan' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tahun_angkatan' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tahun_angkatan' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Tahun akademik
        DB::table('tahun_akademik')->insert([
            [
                'tahun_ajaran' => 'Ganjil 2025/2026',
                'status' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tahun_ajaran' => 'Genap 2025/2026',
                'status' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);

        // Jurusan
        DB::table('jurusan')->insert([
            [
                'nama_jurusan' => 'Teknik Elektro',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jurusan' => 'Teknik Sipil',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jurusan' => 'Teknik Mesin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jurusan' => 'Akuntansi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jurusan' => 'Administrasi Bisnis',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);

        // Program studi
        DB::table('program_studi')->insert([
            //Elektro
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D4 Teknologi Rekayasa Komputer',
                'kode_prodi' => 'TI',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D4 Teknologi Rekayasa Elektronika',
                'kode_prodi' => 'RE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D4 Teknologi Rekayasa Instalasi Listrik',
                'kode_prodi' => 'IL',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D4 Teknik Telekomunikasi',
                'kode_prodi' => 'TE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D3 Teknik Informatika',
                'kode_prodi' => 'IK',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D3 Teknik Elektronika',
                'kode_prodi' => 'EK',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D3 Teknik Listrik',
                'kode_prodi' => 'LT',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_jurusan' => 1,
                'nama_prodi' => 'D3 Teknik Telekomunikasi',
                'kode_prodi' => 'TK',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);

        // Jam awal
        DB::table('jam_awal')->insert([
            [
                'nama_jam' => 1,
                'keterangan' => '07:00-07:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 2,
                'keterangan' => '07:45-08:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 3,
                'keterangan' => '08:30-09:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 4,
                'keterangan' => '09:35-10:20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 5,
                'keterangan' => '10:20-11:05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 6,
                'keterangan' => '11:05-11:50',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 7,
                'keterangan' => '12:30-13:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 8,
                'keterangan' => '13:15-14:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 9,
                'keterangan' => '14:00-14:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 10,
                'keterangan' => '14:45-15:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 11,
                'keterangan' => '16:00-16:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 12,
                'keterangan' => '16:45-17:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 13,
                'keterangan' => '17:30-18:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 14,
                'keterangan' => '18:45-19:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 15,
                'keterangan' => '19:30-20:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 16,
                'keterangan' => '20:15-21:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Jam akhir
        DB::table('jam_akhir')->insert([
            [
                'nama_jam' => 1,
                'keterangan' => '07:00-07:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 2,
                'keterangan' => '07:45-08:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 3,
                'keterangan' => '08:30-09:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 4,
                'keterangan' => '09:35-10:20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 5,
                'keterangan' => '10:20-11:05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 6,
                'keterangan' => '11:05-11:50',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 7,
                'keterangan' => '12:30-13:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 8,
                'keterangan' => '13:15-14:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 9,
                'keterangan' => '14:00-14:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 10,
                'keterangan' => '14:45-15:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 11,
                'keterangan' => '16:00-16:45',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 12,
                'keterangan' => '16:45-17:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 13,
                'keterangan' => '17:30-18:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 14,
                'keterangan' => '18:45-19:30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 15,
                'keterangan' => '19:30-20:15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_jam' => 16,
                'keterangan' => '20:15-21:00',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);


    }
}