<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class PopulationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        // enrollment_all
        DB::table('enrollment_mk_mhs_dsn_rng')->insert([
            // TI-1A
            [
                'id_mata_kuliah' => 1,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 2,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 3,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 4,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 5,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 6,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 7,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 8,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 9,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 10,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 11,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 12,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 13,
                'id_enrollment_kelas' => 1,
                'id_dosen' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-1B
            [
                'id_mata_kuliah' => 1,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 2,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 3,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 4,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 5,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 6,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 7,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 8,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 9,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 10,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 11,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 12,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 13,
                'id_enrollment_kelas' => 2,
                'id_dosen' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-1C
            [
                'id_mata_kuliah' => 1,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 2,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 3,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 4,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 5,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 6,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 7,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 8,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 9,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 10,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 11,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 12,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 13,
                'id_enrollment_kelas' => 3,
                'id_dosen' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //TI-2A
            [
                'id_mata_kuliah' => 14,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 15,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 16,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 17,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 18,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 19,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 20,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 21,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 22,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 23,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 24,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 25,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 26,
                'id_enrollment_kelas' => 4,
                'id_dosen' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-2B
            [
                'id_mata_kuliah' => 14,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 15,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 16,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 17,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 18,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 19,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 20,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 21,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 22,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 23,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 24,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 25,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 26,
                'id_enrollment_kelas' => 5,
                'id_dosen' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-2C
            [
                'id_mata_kuliah' => 14,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 15,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 16,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 17,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 18,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 19,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 20,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 21,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 22,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 23,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 24,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 25,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 26,
                'id_enrollment_kelas' => 6,
                'id_dosen' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-3A
            [
                'id_mata_kuliah' => 27,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 28,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 29,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 30,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 31,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 32,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 33,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 34,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 35,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 36,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 37,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 38,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 39,
                'id_enrollment_kelas' => 7,
                'id_dosen' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-3B
            [
                'id_mata_kuliah' => 27,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 28,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 29,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 30,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 31,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 32,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 33,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 34,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 35,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 36,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 37,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 38,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 39,
                'id_enrollment_kelas' => 8,
                'id_dosen' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-4A
            [
                'id_mata_kuliah' => 40,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 41,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 42,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 43,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 44,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 45,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 46,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 47,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 48,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 49,
                'id_enrollment_kelas' => 9,
                'id_dosen' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-4B
            [
                'id_mata_kuliah' => 40,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 41,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 42,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 43,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 44,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 45,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 46,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 47,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 48,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 49,
                'id_enrollment_kelas' => 10,
                'id_dosen' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // TI-4C
            [
                'id_mata_kuliah' => 40,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 41,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 42,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 43,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 44,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 45,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 46,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 47,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 48,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_mata_kuliah' => 49,
                'id_enrollment_kelas' => 11,
                'id_dosen' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
        DB::table('requirement_dosen')->insert([
            [
                'id_dosen' => 1,
                'jam_mulai' => 1,
                'jam_selesai' => 2,
                'hari' => 'Senin',
                'keterangan' => 'Mengantar anak sekolah',
                'status' => 'Belum Divalidasi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_dosen' => 3,
                'jam_mulai' => 4,
                'jam_selesai' => 7,
                'hari' => 'Rabu',
                'keterangan' => 'Jadwal Kontrol Kesehatan',
                'status' => 'Divalidasi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
                        [
                'id_dosen' => 13,
                'jam_mulai' => 1,
                'jam_selesai' => 2,
                'hari' => 'Jumat',
                'keterangan' => 'Piket Sekretariat',
                'status' => 'Belum Divalidasi',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);
    }
}
